BC-SECURITY/Empire

data/agent/stagers/common/aes.py
lib/common/encryption.py
lib/modules/python/collection/osx/keychaindump_chainbreaker.py

As of Python 3.8, the explicit keyword `digestmod=` in the hmac.new() function is required. Without this, staging process will throw out `HMAC Verification failed` error. 
Tested with Python 3.8.1 and 2.7.17

Python 3.8 compatibility for staging encryption routine

---

lib/modules/powershell/privesc/powerup/allchecks.py

Can't seem to understand why it wanted the bytes and not the string payload.
Tested on the latest Windows 10 build, works fine

PowerUp Invoke-AllChecks Fix

---

lib/common/stagers.py
lib/stagers/osx/application.py

I found 3 bugs during the creation of a stager for OSX running Empire with Python 3.
**Bug 1**
Using Python 3, during the creation of a OSX stager, Empire throws an exception related to a str object passed instead of a byte-like:
```
(Empire) > usestager osx/application
(Empire: stager/osx/application) > set Listener http
(Empire: stager/osx/application) > generate
[!] Exception: a bytes-like object is required, not ‘str'
```
That is caused by the fact the object `cmd[count].segname` is of type byte and the same type is required by `strip` for its argument. 
**Bug 2**
The second bug is related on how Empire opens the templates in `/data/misc/apptemplateResources`. By default Python 3 uses utf8 for encoding and when the template is parsed it throws an exception because it can't decode a …

Fixed stager for OSX and appbundle creation

---

data/agent/agent.py
empire

fixes https://github.com/BC-SECURITY/Empire/issues/88 and also adds "stale" as a property on the agents for convenience

add stale flag to /api/agents and encoding session_key bug

---

README.md
lib/listeners/http.py
lib/listeners/http_com.py
lib/modules/powershell/credentials/mimikatz/cache.py
lib/modules/powershell/credentials/mimikatz/certs.py
lib/modules/powershell/credentials/mimikatz/command.py
lib/modules/powershell/credentials/mimikatz/dcsync.py
lib/modules/powershell/credentials/mimikatz/dcsync_hashdump.py
lib/modules/powershell/credentials/mimikatz/extract_tickets.py
lib/modules/powershell/credentials/mimikatz/golden_ticket.py
lib/modules/powershell/credentials/mimikatz/keys.py
lib/modules/powershell/credentials/mimikatz/logonpasswords.py
lib/modules/powershell/credentials/mimikatz/lsadump.py
lib/modules/powershell/credentials/mimikatz/mimitokens.py
lib/modules/powershell/credentials/mimikatz/pth.py
lib/modules/powershell/credentials/mimikatz/purge.py
lib/modules/powershell/credentials/mimikatz/sam.py
lib/modules/powershell/credentials/mimikatz/silver_ticket.py
lib/modules/powershell/credentials/mimikatz/trust_keys.py
setup/setup_database.py

Reverts BC-SECURITY/Empire#109

Revert "Function name randomization"

---

lib/common/users.py

try to login via the rest api always got me the following error:
HTTP/1.0 500
Content-Type: application/json
Content-Length: 54
Access-Control-Allow-Origin: *
Server: Werkzeug/1.0.0 Python/3.6.9
Date: Mon, 09 Mar 2020 15:48:02 GMT
{"error":"OperationalError('no such column: true',)"}
---------------------------------------------------------
enabled must be check for '1' not 'true' to fix this issue and allow starkiller to work with the latest version of empire.

fix rest login error 500 for starkiller

---

empire

fix rest get config error 500.

fix rest get config error 500.

---

lib/common/packets.py

fix non-ascii filename downloading error.
When download files with non-ascii filename,the 'length' part in the packet is the length of string of the filename,but not bytes of encoded filename,so throw an index-out-of-bounts error

Fix non-ascii filename download bug

---

lib/modules/powershell/persistence/powerbreach/resolver.py

When I execute module "persistence/powerbreach/resolver",
got `[!] Exception: can't concat str to bytes`.
Because `script = script.encode('ascii', 'ignore')` make script be converted to bytes.
So I removed this line to make it works.

Fix exception thrown in module persistence/powerbreach/resolver

---

setup/install.sh
setup/requirements.txt
setup/requirements_libssl1.0.txt
setup/reset.sh

- Fixed issue with m2crypto not installing
- Removed dependency on python 2
- Added missing packages to requirements_libssl1.0.txt
- Updated setup_database.py to run in python3

Updated install script

---

data/module_source/credentials/Invoke-Kerberoast.ps1
data/module_source/situational_awareness/network/powerview.ps1

Hello.
I was just using the `Invoke-Kerberoast` function and have noticed that the format is not correct for JtR. There are two issues, first it does not detect it as the correct format and instead tries to crack it as using a different algorithm (known issue, PowerShellMafia/PowerSploit#310), second when the SPN contains a `:` (such as a port number) it will cause issues with the JtR parser as that delimits the end of the user name. 
It appears the issue is that JtR updated the input format a little in magnumripper/JohnTheRipper#2026 so this PR brings the output format of both `Invoke-Kerberpost.ps1` and `powerview.ps1` into alignment with that.
From my tests, it is working fine for:
```
John the Ripper 1.9.0-jumbo-1 OMP [linux-gnu 64-bit x86_64 AVX2 AC]
Copyright (c) 1996-2019 by Solar …
```

[BUG] Align Invoke-Kerberoast JtR format with magnumripper/JohnTheRipper#2026

---

data/module_source/lateral_movement/Invoke-PortFwd.ps1
lib/modules/powershell/lateral_movement/invoke_portfwd.py

The core code is taken from [decoder-it/psportfwd](https://github.com/decoder-it/psportfwd) which makes it possible to forward a port with no administrative rights required.

Add port forwarding module

---

lib/common/empire.py

Fixed an issue where CLI would ungracefully exit and leave users unable to exit or use Empire.

Fixed CLI stager incorrectly shutting down

---

empire
lib/common/empire.py

Currently, moduleName only displays the moduleName listed in the object. But, using the full directory allows us to call the object again and pull additional information if needed.

Changed moduleName to display full name

---

data/module_source/situational_awareness/network/powermad.ps1
lib/modules/powershell/situational_awareness/network/powermad/get_adidns_permission.py
lib/modules/powershell/situational_awareness/network/powermad/get_adidns_zone.py

Hello there!
In this PR I would like to integrate the [Powermad](https://github.com/Kevin-Robertson/Powermad) set of tools into Empire and propose two modules for querying Active Directory-Integrated DNS (ADIDNS) information:
- get_adidns_zone.py (`Get-ADIDNSZone`) — query ADIDNS zones in the specified domain;
- get_adidns_permission.py (`Get-ADIDNSPermission`) — query a DACL of an ADIDNS node or zone in the specified domain.

Added Powermad modules

---

data/module_source/situational_awareness/network/Invoke-SmbScanner.ps1
lib/modules/powershell/lateral_movement/invoke_psremoting.py
lib/modules/powershell/lateral_movement/invoke_smbexec.py
lib/modules/powershell/situational_awareness/network/smbscanner.py

Fixed some module bugs.
- Added Command to module powershell/lateral_movement/invoke_psremoting
- Fixed Command quoting issue with module powershell/lateral_movement/invoke_smbexec
- Refactored module_source/situational_awareness/network/Invoke-SmbScanner.ps1 to work on modern Windows
- Accompanying changes to associated module: powershell/situational_awareness/network/smbscanner

Bugfixin for smbscanner, psremoting, and smbexec

---

data/module_source/code_execution/Invoke-Assembly.ps1
lib/modules/powershell/code_execution/invoke_assembly.py
lib/modules/powershell/management/invoke_sharpchisel.py

Added Invoke-Assembly, which is a Powershell loader for arbitrary .NET assembly code. It uses the `System.Reflection.Assembly.Load()`, similar to Invoke-Rubeus and Invoke-Seatbelt, and allows running the `Main()` method of any .NET assembly, as long as `Main()` is exported.
Includes:
- Powershell script
- Empire module

Added Invoke assembly module

---

data/agent/agent.py
data/agent/stagers/common/rc4.py
data/agent/stagers/http.py
lib/common/malleable/transaction.py
lib/listeners/http.py
lib/listeners/http_malleable.py

In this PR I fixed various issues with Python launcher for HTTP Malleable listener. They were mostly related to Python2 legacy syntax:
- change `urllib` imports to Python3 way (separate `urllib.request` and `urllib.parse`). This one had to be done in both HTTP malleable listener and in HTTP listener, because malleable acutally inherits from HTTP
- fix encoding issues on bytes-str transformations
- fix minor syntax errors (like lack of newlines or unnecessary quotes)
After changes I tested Python launcher for:
- HTTP listener
- HTTP Malleable with [havex.profile](https://github.com/BC-SECURITY/Malleable-C2-Profiles/blob/master/APT/havex.profile)
- HTTP Malleable with [powruner.profile](https://github.com/BC-SECURITY/Malleable-C2-Profiles/blob/master/APT/powruner.profile)

Make HTTP malleable Python launcher work

---

data/module_source/credentials/Invoke-Kerberoast.ps1

If Kerberos ticket generation fails for the first SPN of a service account, a ticket is requested for the alternate SPNs until a ticket can be generated successfully.

Fix failed ticket generation in Invoke-Kerberoast

---

lib/common/listeners.py

As mentioned (see #454) this fixes the bug in sqlalchemy usage that prevented editing an existing listener.
Now it is working as intended:

Fixed #454 can't change listerner values bug

---

empire/server/server.py

Empire creates a default test account with a password generated using an insecure random number generator (Python's default [`random`](https://docs.python.org/3/library/random.html) based on Mersenne Twister), which as the documentation also points out should never be used in a security context. The RNG's state can be leaked through a variety of other uses through out the application. Due to the leaked state an unauthenticated attacker can potentially recover the RNG's state and then recovery test account's password since it was generated from the same RNG instance.
The user in question is cleaned up, so exploitability is very limited, however best to be safe.
This patch switches the password generation to [`random.SystemRandom`](https://docs.python.org/3/library/random.html#random.SystemR …

Test Account Generated using Insecure RNG

---

empire/server/data/agent/agent.ps1

Multilines output were rendered as single line. The output was sent incorrectly by the Powershell agent.

Corrected the shell output bug (#491)

---

empire/server/data/module_source/situational_awareness/network/powerview.ps1

@Hubbl3 new PR this time with the modified DomainSearcher code, added fine grained pw pol as well for lolz.
Potentially can add LAPS as well but would require more mods, source for LAPS toolkit can be found here: 
https://github.com/leoloobeek/LAPSToolkit/blob/master/LAPSToolkit.ps1
feel free to reject or to modify the function to fit the empire current powerview

added functions for group managed service accounts and fine grained pw pol

---

empire/server/plugins/csharpserver.plugin

Prevents infinite loop when output stream from csharpserver plugin is closed.
Related issue: https://github.com/BC-SECURITY/Empire/issues/609

Exit when output stream closed

---

.github/workflows/lint-and-test.yml

PRs from forks fail because they cannot access secrets. This checks which repo we are in and will not use the token in the repo for checking out in the public repo.

add a fallback checkout that doesn't use a token

---

empire/server/common/module_models.py
empire/server/server.py

Fixes #540 `PydanticModule object has no attribute 'info'` in API module search.
- Checks the search query using `matches` method with an optional parameter where it looks for the term (say, description)
- Returns a dict using the `info` method (`@property`) for the respective modules

Fixes #540 module has no attribute 'info' in API search

---

empire/server/common/helpers.py
empire/server/data/agent/agent.py
empire/server/data/agent/ironpython_agent.py
empire/server/modules/python/persistence/multi/desktopfile.py

**Changes to** `helpers.py`:
The strip_python_comments function had a regex that was stripping away docstrings comments, but docstrings are also used as multi-line strings. This caused multi-line strings to be stripped away from module payload, if it happened to have one, effectively breaking payload.
**Changes to** `desktopfile.py:`:
The module's payload was using the binary mode to write to a file but the input was a string. This works fine with Python 2, but not with Python 3.
**Changes to** `agent.py` **and** `ironpython.py`:
The function that I modified is given a string that has been AES decrypted and UTF-8 encoded, and then parses it to create multiple variables by taking bytes from certain positions. Before being UTF-8 encoded, the string might contain non-ascii characters that …

Fixxed some bugs that prevented some modules from executing correctly.

---

setup/checkout-latest-tag.sh

Shabeng missing is causing some strange errors when the script is executed:
```
┌──(empire3)─(kali㉿kali)-[~/opt/empire3/Empire] 2023-02-13 19:54:14 +0100
└─$ ./setup/checkout-latest-tag.sh
./setup/checkout-latest-tag.sh: 11: [[: not found
./setup/checkout-latest-tag.sh: 11: [[: not found
./setup/checkout-latest-tag.sh: 16: [: unexpected operator
./setup/checkout-latest-tag.sh: 16: [: unexpected operator
Checkout out latest tag: v4.10.0
HEAD is now at f60c62fb Merge pull request #645 from BC-SECURITY/release/4.10.0
```

SHABENG missing

---

empire/server/common/empire.py

Empire still reports version `5.0.0-beta2`
This commit bumps version to `5.0.4`

bump version

---

empire/server/config.yaml

Following docker install
docker pull bcsecurity/empire:latest
docker run -it -p 1337:1337 -p 5000:5000 --volumes-from data --entrypoint /bin/bash bcsecurity/empire:latest
After running on docker:
sudo ./ps-empire server 
get Error:
Update config file to point real working directory (starkiller) instead of starkiller-temp

Fix starkiller error in docker

---

setup/install.sh

Explicitly specify the version of `nimble` to be installed by install.sh to `v0.14.2` where the following bugs are fixed
- https://github.com/nim-lang/nimble/pull/962
- #690 
After fixing, I confirmed that `install.sh` succeeds as follows.
```
[>] Do you want to install Nim and MinGW? It is only needed to generate a Nim stager (y/N)? y
...
choosenim-init: Downloading choosenim-0.8.4_linux_amd64
Installed component 'nim'
Installed component 'nimble'
Installed component 'nimgrep'
Installed component 'nimpretty'
Installed component 'nimsuggest'
Installed component 'testament'
Installed component 'nim-gdb'
Switched to Nim 1.6.12
choosenim-init: ChooseNim installed in /root/.nimble/bin
choosenim-init: You must now ensure that the Nimble bin dir is in your PATH.
choosenim-init: Place the …
```

Fixes install.sh failed when installing Nim

---

docs/quickstart/configuration/client.md

renamed the title from Client to CLI Client (LEGACY) and added a note for users to use Starkiller.

Updating client.md documentation.

---

CHANGELOG.md
empire/server/data/module_source/python/discovery/nameserver.py
empire/server/modules/python/discovery/nameserver.yaml

Add a nameserver check for Linux hosts.

nameserver: discover nameserver within environment of this host

---

CHANGELOG.md
empire/server/data/agent/ironpython_agent.py
empire/server/data/module_source/python/privesc/linuxprivchecker.py

Python 3.12 is getting more chatty about some syntax warnings:
```
/usr/share/powershell-empire/empire/server/data/agent/ironpython_agent.py:1388: SyntaxWarning: invalid escape sequence '\$'
"""
/usr/share/powershell-empire/empire/server/data/module_source/python/privesc/linuxprivchecker.py:336: SyntaxWarning: invalid e
scape sequence '\('
"cmd": "find / \( -wholename '/home/homedir*' -prune \) -o \( -type d -perm -0002 \) -exec ls -ld '{}' ';' 2>/dev/null | gre
p root",
/usr/share/powershell-empire/empire/server/data/module_source/python/privesc/linuxprivchecker.py:341: SyntaxWarning: invalid e
scape sequence '\('
"cmd": "find / \( -wholename '/home/homedir*' -prune \) -o \( -type d -perm -0002 \) -exec ls -ld '{}' ';' 2>/dev/null | gre
p -v root", …
```

Fix various Python 3.12 SyntaxWarning

---

.github/cst-config-docker.yaml
.github/install_tests/cst-config-install-base.yaml
CHANGELOG.md
Dockerfile
docs/quickstart/configuration/client.md
docs/quickstart/configuration/server.md
empire.py
empire/client/src/EmpireCliConfig.py
empire/config_manager.py
empire/server/core/config.py
empire/server/modules/bof/nanodump.py
empire/server/server.py
empire/test/test_zz_reset.py
setup/install.sh

Refactored code to make Empire to be deployed at system-level (multi-user) with no impact on the current approach based on working only in a case Empire is cloned in a user-granted directory.
This PR makes Empire working also in case it is installed in a system directory without changing the current grants. It is possible by refactoring code by following XDG Base Dir specifications.
https://github.com/BC-SECURITY/Empire/issues/756

Support Empire for system-wide deployment

---

CHANGELOG.md
empire/server/core/agent_task_service.py
empire/server/data/agent/agent.py

The MainAgent object of the running agent (self) has been added to globals() in [empire/server/data/agent/agent.py](https://github.com/BC-SECURITY/Empire/blob/main/empire/server/data/agent/agent.py) right before executing the received python statement.
The python statement itself in [empire/server/core/agent_task_service.py](https://github.com/BC-SECURITY/Empire/blob/main/empire/server/core/agent_task_service.py) has been adjusted to edit the delay and jitter attributes of the MainAgent object.
Screenshot of working delay:
#764

Fixing delay/jitter adjustment in python agent (#764)

---

empire/server/modules/powershell/collection/clipboard_monitor.yaml
empire/server/modules/powershell/collection/keylogger.yaml
empire/server/modules/powershell/collection/screenshot.yaml
empire/server/modules/powershell/collection/toasted.yaml
empire/server/modules/powershell/credentials/DomainPasswordSpray.yaml
empire/server/modules/powershell/credentials/credential_injection.yaml
empire/server/modules/powershell/credentials/enum_cred_store.yaml
empire/server/modules/powershell/credentials/get_lapspasswords.yaml
empire/server/modules/powershell/credentials/invoke_internal_monologue.yaml
empire/server/modules/powershell/credentials/invoke_kerberoast.yaml
empire/server/modules/powershell/credentials/invoke_ntlmextract.yaml
empire/server/modules/powershell/credentials/mimikatz/command.yaml
empire/server/modules/powershell/exfiltration/Invoke_ExfilDataToGitHub.yaml
empire/server/modules/powershell/exfiltration/PSRansom.yaml
empire/server/modules/powershell/exfiltration/egresscheck.yaml
empire/server/modules/powershell/exfiltration/exfil_dropbox.yaml

Updated 14 module descriptions to align with Empire 6.0 LLM requirements:
- `DomainPasswordSpray`
- `credential_injection`
- `enum_cred_store`
- `get_lapspasswords`
- `invoke_kerberoast`
- `invoke_ntlmextract`
- `keylogger`
- `toasted`
- `Invoke_ExfilDataToGitHub'
- `exfil_dropbox`
- `egresscheck`
- `invoke_internal_monologue`
- `PSRansom`
- `mimikatz/command`

Module Description Standardization
